# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proyecto_ave2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for proyecto_ave2

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'proyecto_ave2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing


    pod 'react-native-video', :path => '../node_modules/react-native-video'

    pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  end

  target 'proyecto_ave2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  

end
